### ISSUE TITLE
关于qsc-mobile-php（亦即 qsc-mobile-api-v2）地址暴露的问题

### ISSUE THREAD

**Issue by Senorsen** [QSCTech/QSCMobileLegacy#1]
我倾向于给现在的v2加上简单的token验证，各位怎么看

**Comment by Senorsen** [comment]
iOS 旧版本还在用，不能去掉

**Comment by richard1122** [comment]
这不是本来API地址就没意义。。一抓包或者反向 就看出来了。。。

**Comment by xqyww123** [comment]
C# 逆向无压力…囧…

richard notifications@github.com于2015年6月4日周四 上午9:37写道：

**Comment by xqyww123** [comment]
可以加上验证码，让用户输入(雾

Xero Essential xqyww123@gmail.com于2015年6月4日周四 下午1:01写道：
